/**
  ******************************************************************************
  * @file           : main_cpa.c
  * @brief          : Main program for CPA attack capture
  ******************************************************************************
  * @attention
  *
  * This program is designed for a Correlation Power Analysis (CPA) attack.
  * It waits for a plaintext over UART, encrypts it using a fixed key with AES,
  * and sends the ciphertext back. A trigger signal is set high during the
  * AES operation to allow precise power trace acquisition.
  *
  * PROTOCOL:
  * - Host sends: 'P' (1 byte) + Plaintext (16 bytes)
  * - Target sends: 'C' (1 byte) + Ciphertext (16 bytes)
  *
  ******************************************************************************
  */
#include "main.h"
#include "mbedtls.h"
#include "mbedtls/aes.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// Trigger pin definition (e.g., connected to oscilloscope's trigger channel)
#define TRIG_GPIO_Port GPIOB
#define TRIG_Pin       GPIO_PIN_8
#define TRIG_HIGH() HAL_GPIO_WritePin(TRIG_GPIO_Port, TRIG_Pin, GPIO_PIN_SET)
#define TRIG_LOW()  HAL_GPIO_WritePin(TRIG_GPIO_Port, TRIG_Pin, GPIO_PIN_RESET)

/* Private variables ---------------------------------------------------------*/
UART_HandleTypeDef huart2;

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);

// Hardcoded key for the AES encryption. This is the secret we want to find.
static const uint8_t CPA_KEY[16] = {
  0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
  0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c
};

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();
  MX_MBEDTLS_Init();

  mbedtls_aes_context aes_ctx;
  uint8_t cmd;
  uint8_t plaintext[16];
  uint8_t ciphertext[16];
  uint8_t response_buffer[17];

  // Initialize AES context and set the encryption key
  mbedtls_aes_init(&aes_ctx);
  if (mbedtls_aes_setkey_enc(&aes_ctx, CPA_KEY, 128) != 0) {
    Error_Handler();
  }

  // Signal to the host that the device is ready
  const char* ready_msg = "READY\r\n";
  HAL_UART_Transmit(&huart2, (uint8_t*)ready_msg, strlen(ready_msg), HAL_MAX_DELAY);

  /* Infinite loop to process encryption requests */
  while (1)
  {
    // Wait for the command byte 'P'
    if (HAL_UART_Receive(&huart2, &cmd, 1, HAL_MAX_DELAY) != HAL_OK) {
        continue;
    }
    if (cmd != 'P') {
        continue;
    }

    // Receive the 16-byte plaintext
    if (HAL_UART_Receive(&huart2, plaintext, 16, HAL_MAX_DELAY) != HAL_OK) {
        continue;
    }

    // Set trigger high, perform encryption, then set trigger low
    TRIG_HIGH();
    if (mbedtls_aes_crypt_ecb(&aes_ctx, MBEDTLS_AES_ENCRYPT, plaintext, ciphertext) != 0) {
      // In case of AES error, you might want to handle it,
      // but for SCA it might be better to just reset or ignore.
      // For now, we continue, but the trigger will be left high.
      // A more robust implementation would have better error handling.
      Error_Handler();
    }
    TRIG_LOW();

    // Prepare response: 'C' + 16 bytes of ciphertext
    response_buffer[0] = 'C';
    memcpy(&response_buffer[1], ciphertext, 16);

    // Send the response back to the host
    HAL_UART_Transmit(&huart2, response_buffer, 17, HAL_MAX_DELAY);
  }
}

// ============== HAL Initialization Functions (can be generated by CubeMX) =============

/**
  * @brief System Clock Configuration
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 8;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 7;
  RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
  }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief USART2 Initialization Function
  */
static void MX_USART2_UART_Init(void)
{
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief GPIO Initialization Function
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOB, TRIG_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : TRIG_Pin */
  GPIO_InitStruct.Pin = TRIG_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

/**
  * @brief  This function is executed in case of error occurrence.
  */
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
    // Infinite loop on error
  }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
}
#endif /* USE_FULL_ASSERT */
